Mvc20201107/Models/Guesbooks.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Mvc20201107.Models
{
    public class Guesbooks
    {


        [DisplayName("編號:")]

        public int Id { get; set; }

        [DisplayName("名字:")]
        [Required(ErrorMessage ="請輸入名字")]
        [StringLength(20, ErrorMessage ="名子不可以超過20字元")]
        public string Name { get; set; }



        [DisplayName("留言內容:")]
        [Required(ErrorMessage = "請輸入內容")]
        [StringLength(100, ErrorMessage = "留言內容不可以超過100字元")]
        public string Content { get; set; }

        [DisplayName("新增時間:")]
        public DateTime CreateTime { get; set; }
        [DisplayName("回覆內容:")]
        [StringLength(100, ErrorMessage = "留言內容不可以超過100字元")]
        public string Reply { get; set; }

        [DisplayName("回覆時間:")]
        public DateTime? ReplyTime { get; set; }




    }
}

Mvc20201107/ViewModels/GuestbooksViewModel.cs
using Mvc20201107.Models;
using Mvc20201107.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Mvc20201107.ViewModels
{
    public class GuestbooksViewModel
    {
        [DisplayName("收尋")]
        public string Search { get; set; }
        public List<Guesbooks> DataList { get; set; }

        public ForPaging Paging { get; set; }
        


        //public List<Guesbooks> DataList { get; set; }


    }
}

Mvc20201107/Controllers/GuestbooksController.cs
using Mvc20201107.Models;
using Mvc20201107.Services;
using Mvc20201107.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc20201107.Controllers
{
    public class GuestbooksController : Controller
    {
        private readonly GuestbooksDBService GuestbooksService = new GuestbooksDBService();



        public ActionResult Index()
        {

            return View();

        }



        // GET: Guestbooks
        public ActionResult GetDataList(string Search,int Page=1)
        {
            GuestbooksViewModel Data = new GuestbooksViewModel();
            Data.Search = Search;
            Data.Paging = new ForPaging(Page);
            Data.DataList = GuestbooksService.GetDataList(Data.Paging, Data.Search);
            //return View(Data);
            return PartialView(Data);
        }
        [HttpPost]
        public ActionResult GetDataList([Bind(Include ="Search")] GuestbooksViewModel Data)
        {
            return RedirectToAction("GetDataList",new { Search = Data.Search});
        }






        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include ="Name,Content")] Guesbooks Data)
        {
            GuestbooksService.InSertGuestbooks(Data);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int Id)
        {
            Guesbooks Data = GuestbooksService.GetDataById(Id);
            return View(Data);
        }
        [HttpPost]
        public ActionResult Edit(int Id, [Bind(Include ="Name,Content")] Guesbooks UpdateDate)
        {
            if (GuestbooksService.CheckUpdate(Id))
            {
                UpdateDate.Id = Id;
                GuestbooksService.UpdateGuestboooks(UpdateDate);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Reply(int Id)
        {
            Guesbooks Data = GuestbooksService.GetDataById(Id);
            return View(Data);
        }

        [HttpPost]
        public ActionResult Reply(int Id, [Bind(Include ="Reply,ReplyTime")] Guesbooks ReplyData)
        {
            if (GuestbooksService.CheckUpdate(Id))
            {
                ReplyData.Id = Id;
                GuestbooksService.ReplyGuestbooks(ReplyData);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }

        }

        public ActionResult Delete(int Id)
        {
            GuestbooksService.DeleteGuestbooks(Id);
            return RedirectToAction("Index");
        }
       
   










    }
}

Mvc20201107/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc20201107.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Mvc20201107/Views/Guestbooks/Create.cshtml
@model Mvc20201107.Models.Guesbooks


@using (Html.BeginForm("Create","Guestbooks")) 
{
    <h3>新增留言</h3>
    <table>
        <tr>
            <td>
                @Html.LabelFor(Model => Model.Name)
            </td>
            <td>
                @Html.TextBoxFor(Model=>Model.Name)
                @Html.ValidationMessageFor(Model=>Model.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(Model => Model.Content)
            </td>
            <td>
                @Html.TextBoxFor(Model => Model.Content)
                @Html.ValidationMessageFor(Model=>Model.Content)
            </td>

        </tr>
    </table>
    <input type="submit" value="新增留言" />
  
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mvc20201107/Views/Guestbooks/Edit.cshtml
@model Mvc20201107.Models.Guesbooks

@{
    ViewBag.Title = "Edit";
}

@section scripts
    {
        @Scripts.Render("~/Scripts/*")
    }



<h2>Edit</h2>

@using (Html.BeginForm())
{
    <h3>修改留言</h3>
    <table>
        <tr>
            <td>
                @Html.LabelFor(Model=>Model.Name)
            </td>
            <td>
                @Html.TextBoxFor(Model=>Model.Name)
                @Html.ValidationMessageFor(Model=>Model.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(Model=>Model.Content)
            </td>
            <td>
                @Html.TextBoxFor(Model => Model.Content)
                @Html.ValidationMessageFor(Model=>Model.Content)
            </td>
        </tr>
    </table>
    if(Model.ReplyTime == null)
    {
        <input type="submit" value="修改留言" />
    }
    else
    {
        <text>此留言已經回覆無法修改</text>
        @Html.ActionLink("返回列表","Index");

    }
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mvc20201107/Views/Guestbooks/GetDataList.cshtml
@model Mvc20201107.ViewModels.GuestbooksViewModel

<div id="DataList">
    <h2>留言板</h2>
    @using (Ajax.BeginForm("GetDataList", "Guestbooks", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId ="DataList"
    }))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(Model => Model.Search)
                </td>
                <td>
                    @Html.TextBoxFor(Model => Model.Search)
                </td>
                <td>
                    <input type="submit" value="搜尋"/>
                </td>
            </tr>
        </table>
        <table>

            @if (!Model.DataList.Count.Equals(0))
            {
                foreach (var item in Model.DataList)
                {
                    <tr>
                        <td>@Html.DisplayNameFor(Model => Model.DataList[0].Name)</td>
                        <td>@item.Name</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(Model => Model.DataList[0].CreateTime)</td>
                        <td>@item.CreateTime</td>
                    </tr>
                      <tr>
                          <td>@Html.DisplayNameFor(Model => Model.DataList[0].Content)</td>
                          <td colspan="3">@item.Content</td>
                      </tr>
                      <tr>
                          <td>
                              @Html.DisplayNameFor(Model => Model.DataList[0].Reply)
                          </td>
                          <td colspan="3">
                              @item.Reply
                          </td>
                      </tr>
                      <tr>
                          <td>@Html.DisplayNameFor(Model => Model.DataList[0].ReplyTime)</td>
                          <td>@item.ReplyTime</td>
                      </tr>
                      <tr>
                          <td>
                              @Html.ActionLink("修改留言", "Edit", new { Id = item.Id })
                              @Html.ActionLink("回覆留言", "Reply", new { Id = item.Id })
                              @Html.ActionLink("刪除留言", "Delete", new { Id = item.Id })
                          </td>
                      </tr>

                }

            }
            else
            {
                <tr>
                    <td colspan="4">
                        資料庫內查無資料
                    </td>
                </tr>

                <tr>
                    <td>
                        @if(Model.Paging.NowPage > 1)
                        {
                            @Ajax.ActionLink("<<","GetDataList"
                            , new { Page =1 , Search = Model.Search}
                            , new AjaxOptions
                            {
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "DataList"

                            })
                            @Ajax.ActionLink("<", "GetDataList",
                           new {Page = Model.Paging.NowPage-1, Search = Model.Search},
                           new AjaxOptions
                           {
                               InsertionMode = InsertionMode.Replace,
                               UpdateTargetId = "DataList"
                           })
                        }
                    </td>
                    <td>
                        @for (var page = (Model.Paging.NowPage - 6);page<(Model.Paging.NowPage+6);page++)
                        {
                            if((page >0) && (page <= Model.Paging.MaxPage))
                            {
                                if (page==Model.Paging.NowPage)
                                {
                                    <b>@page</b>

                                }
                                else
                                {
                                    @Ajax.ActionLink(page.ToString(),"GetDataList",
                                   new {Page =page , Search = Model.Search},
                                   new AjaxOptions
                                   {
                                       InsertionMode = InsertionMode.Replace,
                                       UpdateTargetId = "DataList"
                                   }
                                )}


                            }



                        }
                    </td>
                    <td>
                        @if (Model.Paging.NowPage < Model.Paging.MaxPage)
                        {
                            @Ajax.ActionLink(">","GetDataList",
                            new {Page = Model.Paging.NowPage +1, Search = Model.Search},
                            new AjaxOptions
                            {
                                InsertionMode =InsertionMode.Replace,
                                UpdateTargetId ="DataList"
                            }

                           )
                           @Ajax.ActionLink(">>","GetDataList",
                           new {Page = Model.Paging.MaxPage, Search = Model.Search},
                           new AjaxOptions
                           {
                               InsertionMode = InsertionMode.Replace,
                               UpdateTargetId ="DataList"

                           }
                          )
                        }

                    </td>

                </tr>



            }


        </table>



    }







</div>

Mvc20201107/Views/Guestbooks/Index.cshtml
@model Mvc20201107.ViewModels.GuestbooksViewModel

@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>

@Html.AntiForgeryToken()

<div id="CreateData">
  @Html.Action("Create")
</div>

@Html.Action("GetDataList")

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mvc20201107/Views/Guestbooks/Reply.cshtml
@model Mvc20201107.Models.Guesbooks

@{
    ViewBag.Title = "回覆留言";
}

<h2>Reply</h2>



@using (Html.BeginForm())
{
    <h3>回覆留言</h3>
    <table>
        <tr>
            <td>
                @Html.LabelFor(Model=>Model.Name)
            </td>
            <td>
                @Html.TextBoxFor(Model =>Model.Name)
                @Html.ValidationMessageFor(Model=>Model.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(Model=>Model.Content)
            </td>
            <td>
                @Html.TextBoxFor(Model =>Model.Content)
                @Html.ValidationMessageFor(Model=>Model.Content)
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(Model=>Model.Reply)
            </td>
            <td>
                @Html.TextBoxFor(Model=>Model.Reply)
                @Html.ValidationMessageFor(Model =>Model.Reply)
            </td>
        </tr>
    </table>

    if(Model.ReplyTime == null)
    {
        <input type="submit" value="回覆留言" />
    }
    else
    {
        <text> 此留言已回覆，請</text>
        @Html.ActionLink("返回列表","Index");
    }
}

@section scripts
    {
        @Scripts.Render("~/Scripts/*");
    
    }

Mvc20201107/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Mvc20201107/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Mvc20201107/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Mvc20201107/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>